version: '3'

services:
  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    build:
      context: .
    command: celery -A edus worker --loglevel=INFO
    environment:
      WAIT_HOSTS: redis:6379
    depends_on:
      - redis
