# Generated by Django 3.1.1 on 2020-09-30 13:57

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('logo', sorl.thumbnail.fields.ImageField(default='images/courses/placeholder.png', upload_to='images/courses/')),
                ('slug', models.SlugField()),
                ('teachers', models.ManyToManyField(related_name='courses', to='members.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_streams', to='courses.course')),
                ('students', models.ManyToManyField(related_name='course_streams', to='members.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('time_start', models.DateTimeField()),
                ('course_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to='courses.coursestream')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to='members.teacher')),
            ],
        ),
    ]
