# Generated by Django 3.1.1 on 2020-09-30 13:57

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('bio', models.TextField()),
                ('avatar', sorl.thumbnail.fields.ImageField(default='images/members/placeholder.png', upload_to='images/members/students/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('bio', models.TextField()),
                ('avatar', sorl.thumbnail.fields.ImageField(default='images/members/placeholder.png', upload_to='images/members/teachers/')),
                ('position', models.CharField(max_length=32)),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
