# Generated by Django 3.1.1 on 2020-09-30 13:59

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default='images/members/avatar.png', upload_to='images/members/students/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default='images/members/avatar.png', upload_to='images/members/teachers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
